import { useId } from 'react'

/**
 * The mark and the lockup, inline and in the supplied colours.
 *
 * GENERATED by scripts/make-logotype.mjs. Run that after changing
 * brand/logo.svg or brand/logotype-source.svg; hand edits here are overwritten.
 * tests/brand.test.ts checks it against the files in brand/ in both directions.
 *
 * Inline rather than <img src="/logo.svg">: the artwork is in the prerendered
 * HTML instead of arriving a request later, which for the thing at the top left
 * of every page is the difference between a logo and a gap where one will be.
 * Both are aria-hidden — they carry nothing a screen reader needs beyond the
 * brand name, which the surrounding markup provides as text.
 *
 * In colour, on purpose and against the brief. §6.2 says the mark is only ever
 * ink or paper and criterion 9 says the logo is never orange, the reasoning
 * being that orange has one job — "press this" — and spending it on a logo
 * blunts the button. That was overruled: the supplied artwork carries three
 * orange cells and a gradient ray across the word, and it ships as drawn.
 * brand/logo-flat.svg still exists for the rasteriser and for any surface that
 * needs the mark to inherit `color`.
 */

export interface BrandArtProps {
  className?: string
}

/**
 * The awning, dissolving into pixels at the lower right. Ratio 0.92.
 */
export function LogoMark({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 270 292"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M197.334 276.038H214.323V292H197.334V276.038Z" fill="#666060" />
      <path d="M163.355 276.038H180.344V292H163.355V276.038Z" fill="#0A0A0A" />
      <path d="M146.367 276.038H163.356V292H146.367V276.038Z" fill="#666060" />
      <path d="M95.4004 276.038H112.389V292H95.4004V276.038Z" fill="#0A0A0A" />
      <path d="M112.391 276.038H129.379V292H112.391V276.038Z" fill="#0A0A0A" />
      <path d="M129.379 276.038H146.368V292H129.379V276.038Z" fill="#0A0A0A" />
      <path d="M163.355 260.075H180.344V276.037H163.355V260.075Z" fill="#666060" />
      <path d="M129.379 260.075H146.368V276.037H129.379V260.075Z" fill="#0A0A0A" />
      <path d="M146.367 260.075H163.356V276.037H146.367V260.075Z" fill="#0A0A0A" />
      <path d="M180.344 260.075H197.332V276.037H180.344V260.075Z" fill="#0A0A0A" />
      <path d="M163.355 244.113H180.344V260.076H163.355V244.113Z" fill="#0A0A0A" />
      <path d="M180.344 244.113H197.332V260.076H180.344V244.113Z" fill="#0A0A0A" />
      <path d="M112.391 244.124H129.379V260.086H112.391V244.124Z" fill="#FF6131" />
      <path d="M129.379 228.161H146.368V244.123H129.379V228.161Z" fill="#FF3E04" />
      <path d="M163.346 212.199H180.334V228.161H163.346V212.199Z" fill="#E54E20" />
      <path
        d="M0 292L135 0L270 292H232.578L154.261 156.58L75.9444 292H0Z"
        fill="#0A0A0A"
      />
    </svg>
  )
}

/**
 * The mark and "wning" beside it, flat. Ratio 2.65.
 *
 * The navigation's lockup. The full one carries a gradient ray through two
 * masks, and at the 34px the bar sets it at that ray is a couple of pixels per
 * letter — all of its weight and none of its effect. These letters are the same
 * forms, respaced to hold together small.
 *
 * The descender is the bottom 25% of the box, so the word sits high inside
 * it: anything vertically centring this has to compensate. See .logo-type.
 */
export function LogoCompact({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 1024.3 386.75"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M197.334 276.038H214.323V292H197.334V276.038Z" fill="#666060" />
      <path d="M163.355 276.038H180.344V292H163.355V276.038Z" fill="#0A0A0A" />
      <path d="M146.367 276.038H163.356V292H146.367V276.038Z" fill="#666060" />
      <path d="M95.4004 276.038H112.389V292H95.4004V276.038Z" fill="#0A0A0A" />
      <path d="M112.391 276.038H129.379V292H112.391V276.038Z" fill="#0A0A0A" />
      <path d="M129.379 276.038H146.368V292H129.379V276.038Z" fill="#0A0A0A" />
      <path d="M163.355 260.075H180.344V276.037H163.355V260.075Z" fill="#666060" />
      <path d="M129.379 260.075H146.368V276.037H129.379V260.075Z" fill="#0A0A0A" />
      <path d="M146.367 260.075H163.356V276.037H146.367V260.075Z" fill="#0A0A0A" />
      <path d="M180.344 260.075H197.332V276.037H180.344V260.075Z" fill="#0A0A0A" />
      <path d="M163.355 244.113H180.344V260.076H163.355V244.113Z" fill="#0A0A0A" />
      <path d="M180.344 244.113H197.332V260.076H180.344V244.113Z" fill="#0A0A0A" />
      <path d="M112.391 244.124H129.379V260.086H112.391V244.124Z" fill="#FF6131" />
      <path d="M129.379 228.161H146.368V244.123H129.379V228.161Z" fill="#FF3E04" />
      <path d="M163.346 212.199H180.334V228.161H163.346V212.199Z" fill="#E54E20" />
      <path
        d="M0 292L135 0L270 292H232.578L154.261 156.58L75.9444 292H0Z"
        fill="#0A0A0A"
      />
      <g transform="translate(270.9 72.55)">
        <path
          d="M0 66L35.615 218.2H67.365L85.8 139.416L104.236 218.2H135.985L171.6 66H143.871L120.111 167.54L96.35 66H75.25L51.49 167.54L27.73 66H0Z"
          fill="#0A0A0A"
        />
        <path
          d="M205.6 218.2V112C205.6 86.595 226.195 66 251.6 66H288.9C314.305 66 334.9 86.595 334.9 112V218.2H307.9V112C307.9 101.507 299.394 93 288.9 93H251.6C241.107 93 232.6 101.507 232.6 112V218.2H205.6Z"
          fill="#0A0A0A"
        />
        <path
          d="M441.9 218.2V112C441.9 86.595 462.495 66 487.9 66H525.2C550.605 66 571.2 86.595 571.2 112V218.2H544.2V112C544.2 101.507 535.694 93 525.2 93H487.9C477.407 93 468.9 101.507 468.9 112V218.2H441.9Z"
          fill="#0A0A0A"
        />
        <path
          d="M677.301 66C719.325 66 753.405 100.071 753.405 142.1V255.51C753.405 287.924 727.125 314.2 694.715 314.2H628.201V287.2H694.715C712.215 287.2 726.405 273.012 726.405 255.51V200.241C700.695 221.954 663.772 224.201 635.618 205.769C607.463 187.336 594.758 152.599 604.375 120.351C613.993 88.103 643.649 66 677.301 66ZM677.301 93C650.184 93 628.201 114.983 628.201 142.1C628.201 169.217 650.184 191.2 677.301 191.2C704.415 191.2 726.405 169.217 726.405 142.1C726.405 114.983 704.415 93 677.301 93Z"
          fill="#0A0A0A"
        />
        <path
          d="M388.4 39C399.169 39 407.9 30.27 407.9 19.5C407.9 8.73 399.169 0 388.4 0C377.63 0 368.9 8.73 368.9 19.5C368.9 30.27 377.63 39 388.4 39Z"
          fill="#0A0A0A"
        />
        <path
          d="M397.436 65.5098H379.436C376.674 65.5098 374.436 67.7483 374.436 70.5098V213.51C374.436 216.271 376.674 218.51 379.436 218.51H397.436C400.197 218.51 402.436 216.271 402.436 213.51V70.5098C402.436 67.7483 400.197 65.5098 397.436 65.5098Z"
          fill="#0A0A0A"
        />
      </g>
    </svg>
  )
}

/**
 * The mark and "wning" beside it, with the ray swept across the word.
 *
 * Ratio 2.51. The g's descender is the bottom 24% of the box, so
 * the word sits high inside it: anything vertically centring this has to
 * compensate. See .logo-type in SiteNav.css.
 *
 * Every id is suffixed with useId. The page renders this twice — the navigation
 * and the foot — and two inline SVGs sharing a mask id do not warn, they just
 * pick one and break the other.
 */
export function Logotype({ className }: BrandArtProps) {
  const uid = useId()
  const maskLetters = `awning-maskLetters-${uid}`
  const maskRay = `awning-maskRay-${uid}`
  const ray0 = `awning-ray0-${uid}`
  const ray1 = `awning-ray1-${uid}`
  const ray2 = `awning-ray2-${uid}`
  const ray3 = `awning-ray3-${uid}`
  const ray4 = `awning-ray4-${uid}`
  const ray5 = `awning-ray5-${uid}`
  const ray6 = `awning-ray6-${uid}`
  const ray7 = `awning-ray7-${uid}`
  const ray8 = `awning-ray8-${uid}`
  const ray9 = `awning-ray9-${uid}`

  return (
    <svg
      className={className}
      viewBox="0 0 970.12 385.98"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M197.465 276.69H214.465V292.69H197.465V276.69Z" fill="#666060" />
      <path d="M163.465 276.69H180.465V292.69H163.465V276.69Z" fill="#0A0A0A" />
      <path d="M146.465 276.69H163.465V292.69H146.465V276.69Z" fill="#666060" />
      <path d="M95.4648 276.69H112.465V292.69H95.4648V276.69Z" fill="#0A0A0A" />
      <path d="M112.465 276.69H129.465V292.69H112.465V276.69Z" fill="#0A0A0A" />
      <path d="M129.465 276.69H146.465V292.69H129.465V276.69Z" fill="#0A0A0A" />
      <path d="M163.465 260.69H180.465V276.69H163.465V260.69Z" fill="#666060" />
      <path d="M129.465 260.69H146.465V276.69H129.465V260.69Z" fill="#0A0A0A" />
      <path d="M146.465 260.69H163.465V276.69H146.465V260.69Z" fill="#0A0A0A" />
      <path d="M180.465 260.69H197.465V276.69H180.465V260.69Z" fill="#0A0A0A" />
      <path d="M163.465 244.69H180.465V260.69H163.465V244.69Z" fill="#0A0A0A" />
      <path d="M180.465 244.69H197.465V260.69H180.465V244.69Z" fill="#0A0A0A" />
      <path d="M112.465 244.7H129.465V260.7H112.465V244.7Z" fill="#FF6131" />
      <path d="M129.465 228.7H146.465V244.7H129.465V228.7Z" fill="#FF3E04" />
      <path d="M163.455 212.7H180.455V228.7H163.455V212.7Z" fill="#E54E20" />
      <path
        d="M0 292.69L135.09 0L270.18 292.69H232.733L154.364 156.95L75.995 292.69H0Z"
        fill="#0A0A0A"
      />
      <mask
        id={maskLetters}
        style={{ maskType: 'alpha' }}
        maskUnits="userSpaceOnUse"
        x="281"
        y="89"
        width="700"
        height="295"
      >
        <path
          d="M281.08 145.746L308.149 290.585L347.768 290.416L366.533 215.302L384.625 290.258L424.245 290.089L452.614 145.012L424.896 145.131L400.711 241.941L377.393 145.334L356.301 145.424L332.116 242.234L308.799 145.628L281.08 145.746Z"
          fill="#0A0A0A"
        />
        <path
          d="M465.797 289.444L466.251 188.297C466.359 164.101 487.034 144.398 512.43 144.29L549.715 144.13C575.11 144.022 595.61 163.548 595.501 187.745L595.047 288.891L568.057 289.007L568.511 187.86C568.556 177.866 560.09 169.801 549.6 169.845L512.314 170.005C501.825 170.05 493.285 178.188 493.24 188.182L492.786 289.328L465.797 289.444Z"
          fill="#0A0A0A"
        />
        <path
          d="M673.718 287.602L674.172 186.456C674.281 162.26 694.956 142.556 720.351 142.448L757.637 142.288C783.032 142.18 803.531 161.707 803.423 185.903L802.969 287.049L775.979 287.165L776.433 186.018C776.478 176.025 768.012 167.959 757.522 168.004L720.236 168.163C709.747 168.208 701.207 176.346 701.162 186.34L700.708 287.487L673.718 287.602Z"
          fill="#0A0A0A"
        />
        <path
          d="M904.366 147.375C946.374 147.196 980.295 179.5 980.115 219.529L979.63 327.542C979.491 358.414 953.109 383.552 920.712 383.69L854.223 383.975L854.339 358.259L920.827 357.975C938.32 357.9 952.566 344.327 952.64 327.658L952.877 275.018C927.084 295.808 890.165 298.106 862.101 280.672C834.036 263.236 821.484 230.206 831.235 199.452C840.987 168.697 870.727 147.519 904.366 147.375ZM904.25 173.09C877.144 173.206 855.075 194.237 854.959 220.064C854.843 245.891 876.724 266.734 903.83 266.618C930.934 266.502 953.009 245.471 953.125 219.644C953.241 193.817 931.354 172.975 904.25 173.09Z"
          fill="#0A0A0A"
        />
        <path
          d="M634.957 126.623C645.721 126.577 654.486 118.225 654.532 107.967C654.579 97.7098 645.888 89.4326 635.123 89.4786C624.358 89.5247 615.594 97.8766 615.547 108.134C615.501 118.392 624.191 126.669 634.957 126.623Z"
          fill="#0A0A0A"
        />
        <path
          d="M644.38 142.773L626.387 142.85C623.626 142.862 621.379 145.003 621.367 147.633L620.756 283.829C620.744 286.459 622.972 288.581 625.733 288.569L643.726 288.492C646.486 288.48 648.733 286.339 648.745 283.709L649.357 147.513C649.368 144.883 647.14 142.761 644.38 142.773Z"
          fill="#0A0A0A"
        />
      </mask>
      <g mask={`url(#${maskLetters})`}>
        <mask
          id={maskRay}
          style={{ maskType: 'alpha' }}
          maskUnits="userSpaceOnUse"
          x="-2208"
          y="-1647"
          width="28392"
          height="1973"
        >
          <path
            d="M-2207.18 325.106L22712.4 -1646.9L23235.6 -1458.1L-2207.18 325.106Z"
            fill={`url(#${ray0})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.16 325.106L23363.2 -1406.88L23688.8 -1264.38L-2207.16 325.106Z"
            fill={`url(#${ray1})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.04 325.103L23798 -1211.97L24182.9 -999.412L-2207.04 325.103Z"
            fill={`url(#${ray2})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.13 325.105L24245.8 -959.08L24468.9 -796.389L-2207.13 325.105Z"
            fill={`url(#${ray3})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.1 325.106L24525.2 -748.558L24741.5 -514.045L-2207.1 325.106Z"
            fill={`url(#${ray4})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.15 325.106L24765.2 -479.284L24851.1 -311.663L-2207.15 325.106Z"
            fill={`url(#${ray5})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.15 325.106L24862.9 -276.598L24887.8 -22.8697L-2207.15 325.106Z"
            fill={`url(#${ray6})`}
            fillOpacity="0.7"
          />
          <path
            d="M-2207.16 325.105L24884 5.419L26184 75.6033L-2207.16 325.105Z"
            fill={`url(#${ray7})`}
            fillOpacity="0.7"
          />
        </mask>
        <g mask={`url(#${maskRay})`}>
          <rect x="276.998" y="92" width="720" height="201" fill="#D9D9D9" />
          <rect
            x="276.998"
            y="92"
            width="720"
            height="201"
            fill={`url(#${ray8})`}
            fillOpacity="0.9"
          />
          <rect x="276.998" y="92" width="720" height="201" fill="#D9D9D9" />
          <rect
            x="276.998"
            y="92"
            width="720"
            height="201"
            fill={`url(#${ray9})`}
            fillOpacity="0.9"
          />
        </g>
      </g>
      <path
        d="M271.08 147.746L298.149 292.585L337.768 292.416L356.533 217.302L374.625 292.258L414.245 292.089L442.614 147.012L414.896 147.131L390.711 243.941L367.393 147.334L346.301 147.424L322.116 244.234L298.799 147.628L271.08 147.746Z"
        fill="#0A0A0A"
      />
      <path
        d="M455.797 291.444L456.251 190.297C456.359 166.101 477.034 146.398 502.43 146.29L539.715 146.13C565.11 146.022 585.61 165.548 585.501 189.745L585.047 290.891L558.057 291.007L558.511 189.86C558.556 179.866 550.09 171.801 539.6 171.845L502.314 172.005C491.825 172.05 483.285 180.188 483.24 190.182L482.786 291.328L455.797 291.444Z"
        fill="#0A0A0A"
      />
      <path
        d="M663.718 289.602L664.172 188.456C664.281 164.26 684.956 144.556 710.351 144.448L747.637 144.288C773.032 144.18 793.531 163.707 793.423 187.903L792.969 289.049L765.979 289.165L766.433 188.018C766.478 178.025 758.012 169.959 747.522 170.004L710.236 170.163C699.747 170.208 691.207 178.346 691.162 188.34L690.708 289.487L663.718 289.602Z"
        fill="#0A0A0A"
      />
      <path
        d="M894.366 149.375C936.374 149.196 970.295 181.5 970.115 221.529L969.63 329.542C969.491 360.414 943.109 385.552 910.712 385.69L844.223 385.975L844.339 360.259L910.827 359.975C928.32 359.9 942.566 346.327 942.64 329.658L942.877 277.018C917.084 297.808 880.165 300.106 852.101 282.672C824.036 265.236 811.484 232.206 821.235 201.452C830.987 170.697 860.727 149.519 894.366 149.375ZM894.25 175.09C867.144 175.206 845.075 196.237 844.959 222.064C844.843 247.891 866.724 268.734 893.83 268.618C920.934 268.502 943.009 247.471 943.125 221.644C943.241 195.817 921.354 174.975 894.25 175.09Z"
        fill="#0A0A0A"
      />
      <path
        d="M624.959 128.623C635.723 128.577 644.488 120.225 644.534 109.967C644.581 99.7098 635.89 91.4326 625.125 91.4786C614.359 91.5247 605.595 99.8766 605.549 110.134C605.503 120.392 614.193 128.669 624.959 128.623Z"
        fill="#0A0A0A"
      />
      <path
        d="M634.382 144.773L616.389 144.85C613.628 144.862 611.381 147.004 611.369 149.634L610.758 285.829C610.746 288.459 612.974 290.582 615.735 290.57L633.728 290.493C636.488 290.481 638.735 288.339 638.747 285.709L639.358 149.514C639.37 146.884 637.142 144.761 634.382 144.773Z"
        fill="#0A0A0A"
      />
      <defs>
        <radialGradient
          id={ray0}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.18 325.106) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray1}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.16 325.106) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray2}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.04 325.102) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.33" stopColor="#FF6131" />
          <stop offset="0.66" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray3}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.13 325.105) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.33" stopColor="#FF6131" />
          <stop offset="0.66" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray4}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.1 325.106) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray5}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.15 325.106) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.33" stopColor="#FF6131" />
          <stop offset="0.66" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray6}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.15 325.106) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray7}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(-2207.16 325.105) rotate(-0.9) scale(21681.7 3235.69)"
        >
          <stop offset="0.33" stopColor="#FF6131" />
          <stop offset="0.66" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray8}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(276.998 231.569) scale(576.107 2559.64)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
        <radialGradient
          id={ray9}
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(276.998 231.569) scale(576.107 2559.64)"
        >
          <stop offset="0.3" stopColor="#FF6131" />
          <stop offset="0.62" stopColor="#FF3E04" />
          <stop offset="1" stopColor="#FF3B00" />
        </radialGradient>
      </defs>
    </svg>
  )
}
