/**
 * The mark and the lockup, inline.
 *
 * GENERATED by scripts/make-logotype.mjs. Run that after changing
 * brand/logo.svg or brand/logotype-source.svg; hand edits here are overwritten.
 * Kept deliberately thin so there is no reason to edit it.
 * tests/brand.test.ts checks it against the files in brand/ in both directions.
 *
 * Inline rather than <img src="/logo.svg">: these inherit `color`, so one
 * drawing serves both paper and ink; they are present in the prerendered HTML
 * instead of arriving a request later; and the prerender has no browser to fetch
 * with. Both are aria-hidden — they carry nothing a screen reader needs beyond
 * the brand name, which the surrounding markup provides as text.
 *
 * Monochrome on purpose. The artwork carries three orange cells and they stay
 * in brand/logo-full.svg, which is for the Open Graph card. Orange on the site
 * means "press this", and nobody needs to press the logo.
 */

export interface BrandArtProps {
  className?: string
}

/**
 * The awning, dissolving into pixels at the lower right. Ratio 0.92.
 */
export function LogoMark({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 270 292"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M197.334 276.038H214.323V292H197.334V276.038Z" />
      <path d="M163.355 276.038H180.344V292H163.355V276.038Z" />
      <path d="M146.367 276.038H163.356V292H146.367V276.038Z" />
      <path d="M95.4004 276.038H112.389V292H95.4004V276.038Z" />
      <path d="M112.391 276.038H129.379V292H112.391V276.038Z" />
      <path d="M129.379 276.038H146.368V292H129.379V276.038Z" />
      <path d="M163.355 260.075H180.344V276.037H163.355V260.075Z" />
      <path d="M129.379 260.075H146.368V276.037H129.379V260.075Z" />
      <path d="M146.367 260.075H163.356V276.037H146.367V260.075Z" />
      <path d="M180.344 260.075H197.332V276.037H180.344V260.075Z" />
      <path d="M163.355 244.113H180.344V260.076H163.355V244.113Z" />
      <path d="M180.344 244.113H197.332V260.076H180.344V244.113Z" />
      <path d="M112.391 244.124H129.379V260.086H112.391V244.124Z" />
      <path d="M129.379 228.161H146.368V244.123H129.379V228.161Z" />
      <path d="M163.346 212.199H180.334V228.161H163.346V212.199Z" />
      <path d="M0 292L135 0L270 292H232.578L154.261 156.58L75.9444 292H0Z" />
    </svg>
  )
}

/**
 * The mark and "wning" beside it.
 *
 * Ratio 2.51. The g's descender is the bottom 24% of the box, so
 * the word sits high inside it: anything vertically centring this has to
 * compensate. See .logo-type in SiteNav.css.
 */
export function Logotype({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 970.12 385.98"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M197.465 276.69H214.465V292.69H197.465V276.69Z" />
      <path d="M163.465 276.69H180.465V292.69H163.465V276.69Z" />
      <path d="M146.465 276.69H163.465V292.69H146.465V276.69Z" />
      <path d="M95.4648 276.69H112.465V292.69H95.4648V276.69Z" />
      <path d="M112.465 276.69H129.465V292.69H112.465V276.69Z" />
      <path d="M129.465 276.69H146.465V292.69H129.465V276.69Z" />
      <path d="M163.465 260.69H180.465V276.69H163.465V260.69Z" />
      <path d="M129.465 260.69H146.465V276.69H129.465V260.69Z" />
      <path d="M146.465 260.69H163.465V276.69H146.465V260.69Z" />
      <path d="M180.465 260.69H197.465V276.69H180.465V260.69Z" />
      <path d="M163.465 244.69H180.465V260.69H163.465V244.69Z" />
      <path d="M180.465 244.69H197.465V260.69H180.465V244.69Z" />
      <path d="M112.465 244.7H129.465V260.7H112.465V244.7Z" />
      <path d="M129.465 228.7H146.465V244.7H129.465V228.7Z" />
      <path d="M163.455 212.7H180.455V228.7H163.455V212.7Z" />
      <path d="M0 292.69L135.09 0L270.18 292.69H232.733L154.364 156.95L75.995 292.69H0Z" />
      <path d="M271.08 147.746L298.149 292.585L337.768 292.416L356.533 217.302L374.625 292.258L414.245 292.089L442.614 147.012L414.896 147.131L390.711 243.941L367.393 147.334L346.301 147.424L322.116 244.234L298.799 147.628L271.08 147.746Z" />
      <path d="M455.797 291.444L456.251 190.297C456.359 166.101 477.034 146.398 502.43 146.29L539.715 146.13C565.11 146.022 585.61 165.548 585.501 189.745L585.047 290.891L558.057 291.007L558.511 189.86C558.556 179.866 550.09 171.801 539.6 171.845L502.314 172.005C491.825 172.05 483.285 180.188 483.24 190.182L482.786 291.328L455.797 291.444Z" />
      <path d="M663.718 289.602L664.172 188.456C664.281 164.26 684.956 144.556 710.351 144.448L747.637 144.288C773.032 144.18 793.531 163.707 793.423 187.903L792.969 289.049L765.979 289.165L766.433 188.018C766.478 178.025 758.012 169.959 747.522 170.004L710.236 170.163C699.747 170.208 691.207 178.346 691.162 188.34L690.708 289.487L663.718 289.602Z" />
      <path d="M894.366 149.375C936.374 149.196 970.295 181.5 970.115 221.529L969.63 329.542C969.491 360.414 943.109 385.552 910.712 385.69L844.223 385.975L844.339 360.259L910.827 359.975C928.32 359.9 942.566 346.327 942.64 329.658L942.877 277.018C917.084 297.808 880.165 300.106 852.101 282.672C824.036 265.236 811.484 232.206 821.235 201.452C830.987 170.697 860.727 149.519 894.366 149.375ZM894.25 175.09C867.144 175.206 845.075 196.237 844.959 222.064C844.843 247.891 866.724 268.734 893.83 268.618C920.934 268.502 943.009 247.471 943.125 221.644C943.241 195.817 921.354 174.975 894.25 175.09Z" />
      <path d="M624.959 128.623C635.723 128.577 644.488 120.225 644.534 109.967C644.581 99.7098 635.89 91.4326 625.125 91.4786C614.359 91.5247 605.595 99.8766 605.549 110.134C605.503 120.392 614.193 128.669 624.959 128.623Z" />
      <path d="M634.382 144.773L616.389 144.85C613.628 144.862 611.381 147.004 611.369 149.634L610.758 285.829C610.746 288.459 612.974 290.582 615.735 290.57L633.728 290.493C636.488 290.481 638.735 288.339 638.747 285.709L639.358 149.514C639.37 146.884 637.142 144.761 634.382 144.773Z" />
    </svg>
  )
}
