/**
 * The mark and the logotype, inline.
 *
 * GENERATED by scripts/make-logotype.mjs. Run that after changing brand/logo.svg
 * or any metric in it; hand edits here are overwritten. Kept deliberately thin
 * so there is no reason to edit it. tests/brand.test.ts checks it against the
 * files in brand/ in both directions.
 *
 * Inline rather than <img src="/logo.svg">: these inherit `color`, so one
 * drawing serves both paper and ink; they are present in the prerendered HTML
 * instead of arriving a request later; and the prerender has no browser to fetch
 * with. Both are aria-hidden — they carry nothing a screen reader needs beyond
 * the brand name, which the surrounding markup provides as text.
 */

export interface BrandArtProps {
  className?: string
}

/** Ratio 0.92, so height drives width. */
export function LogoMark({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 12 13"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M6 0L12 13H10.3301L6.86603 7.13726L3.40193 13H0L6 0Z" />
    </svg>
  )
}

/**
 * The name drawn as letters, with the mark standing in for the capital A, and
 * the i drawn as a key.
 *
 * Ratio 2.72. The g's descender is the bottom 25% of the box, so
 * the word sits high inside it: anything vertically centring this has to
 * compensate. See .logo-type in SiteNav.css.
 */
export function Logotype({ className }: BrandArtProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 1057.15 388.69"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M135.09 0L270.18 292.69L232.58 292.69L154.59 160.7L76.59 292.69L0 292.69L135.09 0Z" />
      <path d="M316.18 140.5L362.68 292.69L409.18 140.5L380.95 140.5L362.68 200.29L344.41 140.5Z" />
      <path d="M380.95 140.5L427.45 292.69L473.95 140.5L445.72 140.5L427.45 200.29L409.18 140.5Z" />
      <path d="M495.95 292.69L495.95 200.5C495.95 167.36 522.81 140.5 555.95 140.5C589.09 140.5 615.95 167.36 615.95 200.5L615.95 292.69L588.95 292.69L588.95 200.5C588.95 182.27 574.18 167.5 555.95 167.5C537.72 167.5 522.95 182.27 522.95 200.5L522.95 292.69Z" />
      <path d="M713.95 61.5C730.52 61.5 743.95 74.93 743.95 91.5C743.95 108.06 730.52 121.5 713.95 121.5C697.38 121.5 683.95 108.06 683.95 91.5C683.95 74.93 697.38 61.5 713.95 61.5ZM713.95 78.5C706.77 78.5 700.95 84.32 700.95 91.5C700.95 98.67 706.77 104.5 713.95 104.5C721.13 104.5 726.95 98.67 726.95 91.5C726.95 84.32 721.13 78.5 713.95 78.5Z" />
      <path d="M683.95 156.5L729.95 156.5L729.95 174.5L683.95 174.5Z" />
      <path d="M669.95 184.5L729.95 184.5L729.95 202.5L669.95 202.5Z" />
      <path d="M655.95 212.5L729.95 212.5L729.95 230.5L655.95 230.5Z" />
      <path d="M697.95 140.5L729.95 140.5L729.95 292.69L697.95 292.69Z" />
      <path d="M760.95 292.69L760.95 200.5C760.95 167.36 787.81 140.5 820.95 140.5C854.09 140.5 880.95 167.36 880.95 200.5L880.95 292.69L853.95 292.69L853.95 200.5C853.95 182.27 839.18 167.5 820.95 167.5C802.72 167.5 787.95 182.27 787.95 200.5L787.95 292.69Z" />
      <path d="M981.05 140.5C1023.08 140.5 1057.15 174.57 1057.15 216.59C1057.15 258.62 1023.08 292.69 981.05 292.69C939.02 292.69 904.95 258.62 904.95 216.59C904.95 174.57 939.02 140.5 981.05 140.5ZM981.05 167.5C953.93 167.5 931.95 189.48 931.95 216.59C931.95 243.71 953.93 265.69 981.05 265.69C1008.17 265.69 1030.15 243.71 1030.15 216.59C1030.15 189.48 1008.17 167.5 981.05 167.5Z" />
      <path d="M1030.15 140.5L1057.15 140.5L1057.15 341.19C1057.15 367.43 1035.88 388.69 1009.65 388.69L992.11 388.69L979.65 361.69L1009.65 361.69C1020.97 361.69 1030.15 352.52 1030.15 341.19L1030.15 140.5Z" />
    </svg>
  )
}
